// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Operations.Infrastructure.Database;

#nullable disable

namespace Operations.Infrastructure.Database.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    [Migration("20250519180227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operaciones")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Operations.Domain.AuxiliaryInformations.AuxiliaryInformation", b =>
                {
                    b.Property<long>("AuxiliaryInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuxiliaryInformationId"));

                    b.Property<int>("CertificationStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("estado_certificacion_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<long>("ClientOperationId")
                        .HasColumnType("bigint")
                        .HasColumnName("operacion_cliente_id");

                    b.Property<int>("CollectionAccount")
                        .HasColumnType("integer")
                        .HasColumnName("cuenta_recaudo");

                    b.Property<string>("CollectionBank")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("banco_recaudo");

                    b.Property<int>("CollectionMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("metodo_recaudo_id");

                    b.Property<int>("ContingentWithholding")
                        .HasColumnType("integer")
                        .HasColumnName("retencion_contingente");

                    b.Property<DateTime>("DepositDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_consignacion");

                    b.Property<int>("OriginId")
                        .HasColumnType("integer")
                        .HasColumnName("origen_id");

                    b.Property<JsonDocument>("PaymentMethodDetail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalle_forma_pago");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pago_id");

                    b.Property<string>("SalesUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_comercial");

                    b.Property<int>("TaxConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condicion_tributaria_id");

                    b.Property<JsonDocument>("VerifiableMedium")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("medio_verificable");

                    b.HasKey("AuxiliaryInformationId");

                    b.ToTable("informacion_auxiliar", "operaciones");
                });

            modelBuilder.Entity("Operations.Domain.ClientOperations.ClientOperation", b =>
                {
                    b.Property<long>("ClientOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ClientOperationId"));

                    b.Property<int>("AffiliateId")
                        .HasColumnType("integer")
                        .HasColumnName("afiliado_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("ObjectiveId")
                        .HasColumnType("integer")
                        .HasColumnName("objetivo_id");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer")
                        .HasColumnName("portafolio_id");

                    b.Property<int>("SubtransactionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("subtipotransaccion_id");

                    b.HasKey("ClientOperationId");

                    b.ToTable("operaciones_clientes", "operaciones");
                });

            modelBuilder.Entity("Operations.Domain.ConfigurationParameters.ConfigurationParameter", b =>
                {
                    b.Property<int>("ConfigurationParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigurationParameterId"));

                    b.Property<bool>("Editable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("editable");

                    b.Property<string>("HomologationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_homologacion");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("padre_id");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<bool>("System")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sistema");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("categoria")
                        .HasColumnName("tipo");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("ConfigurationParameterId");

                    b.HasIndex("ParentId");

                    b.ToTable("parametros_configuracion", "operaciones");
                });

            modelBuilder.Entity("Operations.Domain.ConfigurationParameters.ConfigurationParameter", b =>
                {
                    b.HasOne("Operations.Domain.ConfigurationParameters.ConfigurationParameter", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Operations.Domain.ConfigurationParameters.ConfigurationParameter", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
