CREATE TABLE cierre.operaciones_cliente (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fecha_radicacion timestamp with time zone NOT NULL,
    afiliado_id integer NOT NULL,
    objetivo_id integer NOT NULL,
    portafolio_id integer NOT NULL,
    valor numeric(19,2) NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    subtipo_transaccion_id bigint NOT NULL,
    fecha_aplicacion timestamp with time zone NOT NULL,
    CONSTRAINT "PK_operaciones_cliente" PRIMARY KEY (id)
);

CREATE TABLE cierre.rendimientos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    portafolio_id integer NOT NULL,
    ingresos numeric(19,2) NOT NULL,
    gastos numeric(19,2) NOT NULL,
    comisiones numeric(19,2) NOT NULL,
    costos numeric(19,2) NOT NULL,
    rendimientos_abonar numeric(19,2) NOT NULL,
    fecha_cierre timestamp with time zone NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    cerrado boolean NOT NULL,
    CONSTRAINT "PK_rendimientos" PRIMARY KEY (id)
);

CREATE TABLE cierre.rendimientos_fideicomisos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fideicomiso_id integer NOT NULL,
    portafolio_id integer NOT NULL,
    fecha_cierre timestamp with time zone NOT NULL,
    participacion numeric(38,16) NOT NULL,
    unidades numeric(38,16) NOT NULL,
    rendimientos numeric(19,2) NOT NULL,
    saldo_precierre numeric(19,2) NOT NULL,
    saldo_cierre numeric(19,2) NOT NULL,
    ingresos numeric(19,2) NOT NULL,
    gastos numeric(19,2) NOT NULL,
    comisiones numeric(19,2) NOT NULL,
    costo numeric(19,2) NOT NULL,
    capital numeric(19,2) NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    retencion_contingente numeric(19,2) NOT NULL,
    retencion_rendimiento numeric(19,2) NOT NULL,
    CONSTRAINT "PK_rendimientos_fideicomisos" PRIMARY KEY (id)
);

CREATE TABLE cierre.valoracion_portafolio (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    portafolio_id integer NOT NULL,
    fecha_cierre timestamp with time zone NOT NULL,
    valor numeric(19,2) NOT NULL,
    unidades numeric(38,16) NOT NULL,
    valor_unidad numeric(19,2) NOT NULL,
    rendimiento_bruto_unidad numeric(38,16) NOT NULL,
    costo_unidad numeric(38,16) NOT NULL,
    rentabilidad_diaria numeric(38,16) NOT NULL,
    operaciones_entrada numeric(19,2) NOT NULL,
    operaciones_salida numeric(19,2) NOT NULL,
    fecha_proceso date NOT NULL,
    cerrado boolean NOT NULL,
    CONSTRAINT "PK_valoracion_portafolio" PRIMARY KEY (id)
);

CREATE TABLE cierre.detalle_rendimientos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    rendimiento_id bigint NOT NULL,
    portafolio_id integer NOT NULL,
    fecha_cierre timestamp with time zone NOT NULL,
    fuente character varying(50) NOT NULL,
    concepto jsonb NOT NULL,
    ingresos numeric(19,2) NOT NULL,
    gastos numeric(19,2) NOT NULL,
    comisiones numeric(19,2) NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    cerrado boolean NOT NULL,
    CONSTRAINT "PK_detalle_rendimientos" PRIMARY KEY (id),
    CONSTRAINT "FK_detalle_rendimientos_rendimientos_rendimiento_id" FOREIGN KEY (rendimiento_id) REFERENCES cierre.rendimientos (id) ON DELETE CASCADE
);

CREATE INDEX "IX_pyg_concepto_id" ON cierre.pyg (concepto_id);

CREATE INDEX "IX_detalle_rendimientos_rendimiento_id" ON cierre.detalle_rendimientos (rendimiento_id);

ALTER TABLE cierre.pyg ADD CONSTRAINT "FK_pyg_conceptos_pyg_concepto_id" FOREIGN KEY (concepto_id) REFERENCES cierre.conceptos_pyg (id) ON DELETE CASCADE;

INSERT INTO cierre."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250627140301_NewEntities', '9.0.3');


