CREATE TABLE cierre.rendimientos_por_distribuir (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fideicomiso_id bigint NOT NULL,
    portafolio_id integer NOT NULL,
    fecha_cierre timestamp with time zone NOT NULL,
    fecha_aplicacion timestamp with time zone NOT NULL,
    participacion numeric(38,16) NOT NULL,
    rendimientos numeric(19,2) NOT NULL,
    concepto jsonb NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    CONSTRAINT "PK_rendimientos_por_distribuir" PRIMARY KEY (id)
);

INSERT INTO cierre."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251029191020_CreateTableYieldToDistribute', '9.0.3');


