DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'uuid-ossp') THEN
        CREATE EXTENSION "uuid-ossp";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'closing') THEN
        CREATE SCHEMA closing;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'cierre') THEN
        CREATE SCHEMA cierre;
    END IF;
END $$;
CREATE TABLE IF NOT EXISTS cierre."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'cierre') THEN
        CREATE SCHEMA cierre;
    END IF;
END $$;

CREATE TABLE cierre.conceptos_pyg (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    concepto text NOT NULL,
    naturaleza text NOT NULL,
    admite_negativo boolean NOT NULL,
    CONSTRAINT "PK_conceptos_pyg" PRIMARY KEY (id)
);

CREATE TABLE cierre.parametros_configuracion (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    uuid uuid NOT NULL DEFAULT (uuid_generate_v4()),
    nombre character varying(100) NOT NULL,
    padre_id integer,
    estado boolean NOT NULL DEFAULT TRUE,
    tipo character varying(50) NOT NULL DEFAULT 'categoria',
    editable boolean NOT NULL DEFAULT TRUE,
    sistema boolean NOT NULL DEFAULT FALSE,
    metadata jsonb NOT NULL DEFAULT ('{}'),
    codigo_homologacion character varying(20) NOT NULL,
    CONSTRAINT "PK_parametros_configuracion" PRIMARY KEY (id),
    CONSTRAINT "FK_parametros_configuracion_parametros_configuracion_padre_id" FOREIGN KEY (padre_id) REFERENCES cierre.parametros_configuracion (id) ON DELETE RESTRICT
);

CREATE TABLE cierre.pyg (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    portafolio_id integer NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    fecha_efectiva timestamp with time zone NOT NULL,
    concepto_id bigint NOT NULL,
    valor numeric(19,2) NOT NULL,
    fuente text NOT NULL,
    CONSTRAINT "PK_pyg" PRIMARY KEY (id)
);

CREATE INDEX "IX_parametros_configuracion_padre_id" ON cierre.parametros_configuracion (padre_id);

INSERT INTO cierre."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250620191551_InitialCreate', '9.0.3');


