// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Products.Infrastructure.Database;

#nullable disable

namespace Products.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20250609180229_ProductsSchemaUpdate")]
    partial class ProductsSchemaUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("productos")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Products.Domain.AlternativePortfolios.AlternativePortfolio", b =>
                {
                    b.Property<int>("AlternativePortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlternativePortfolioId"));

                    b.Property<int>("AlternativeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCollector")
                        .HasColumnType("boolean")
                        .HasColumnName("recaudador");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.HasKey("AlternativePortfolioId");

                    b.HasIndex("AlternativeId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("alternativas_portafolios", "productos");
                });

            modelBuilder.Entity("Products.Domain.Alternatives.Alternative", b =>
                {
                    b.Property<int>("AlternativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlternativeId"));

                    b.Property<int>("AlternativeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_alternativa_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("HomologatedCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_homologado)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("PlanFundId")
                        .HasColumnType("integer")
                        .HasColumnName("planes_fondo_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.HasKey("AlternativeId");

                    b.HasIndex("PlanFundId");

                    b.ToTable("alternativas", "productos");
                });

            modelBuilder.Entity("Products.Domain.Banks.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("BankId");

                    b.ToTable("bancos", "productos");
                });

            modelBuilder.Entity("Products.Domain.Cities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("CityId");

                    b.ToTable("ciudades", "productos");
                });

            modelBuilder.Entity("Products.Domain.Commercials.Commercial", b =>
                {
                    b.Property<int>("CommercialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommercialId"));

                    b.Property<string>("HomologatedCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_homologado");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefijo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.HasKey("CommercialId");

                    b.ToTable("comerciales", "productos");
                });

            modelBuilder.Entity("Products.Domain.ConfigurationParameters.ConfigurationParameter", b =>
                {
                    b.Property<int>("ConfigurationParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigurationParameterId"));

                    b.Property<bool>("Editable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("editable");

                    b.Property<string>("HomologationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_homologacion");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("padre_id");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<bool>("System")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sistema");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("categoria")
                        .HasColumnName("tipo");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("ConfigurationParameterId");

                    b.HasIndex("ParentId");

                    b.ToTable("parametros_configuracion", "productos");
                });

            modelBuilder.Entity("Products.Domain.Objectives.Objective", b =>
                {
                    b.Property<int>("ObjectiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ObjectiveId"));

                    b.Property<int>("AffiliateId")
                        .HasColumnType("integer")
                        .HasColumnName("afiliado_id");

                    b.Property<int>("AlternativeId")
                        .HasColumnType("integer")
                        .HasColumnName("alternativa_id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("saldo");

                    b.Property<int>("CommercialId")
                        .HasColumnType("integer")
                        .HasColumnName("comercial_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("CurrentOfficeId")
                        .HasColumnType("integer")
                        .HasColumnName("oficina_actual_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("ObjectiveTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_objetivo_id");

                    b.Property<int>("OpeningOfficeId")
                        .HasColumnType("integer")
                        .HasColumnName("oficina_apertura_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.HasKey("ObjectiveId");

                    b.HasIndex("AlternativeId");

                    b.HasIndex("CommercialId");

                    b.ToTable("objetivos", "productos");
                });

            modelBuilder.Entity("Products.Domain.Offices.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfficeId"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("ciudad_id");

                    b.Property<string>("HomologatedCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_homologado");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefijo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.HasKey("OfficeId");

                    b.ToTable("oficinas", "productos");
                });

            modelBuilder.Entity("Products.Domain.PensionFunds.PensionFund", b =>
                {
                    b.Property<int>("PensionFundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PensionFundId"));

                    b.Property<string>("HomologatedCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_homologado");

                    b.Property<int>("IdentificationNumber")
                        .HasColumnType("integer")
                        .HasColumnName("identificacion");

                    b.Property<int>("IdentificationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_identificacion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_corto");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.HasKey("PensionFundId");

                    b.ToTable("fondos_voluntarios_pensiones", "productos");
                });

            modelBuilder.Entity("Products.Domain.PlanFunds.PlanFund", b =>
                {
                    b.Property<int>("PlanFundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanFundId"));

                    b.Property<int>("PensionFundId")
                        .HasColumnType("integer")
                        .HasColumnName("fondo_id");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.HasKey("PlanFundId");

                    b.HasIndex("PensionFundId");

                    b.HasIndex("PlanId");

                    b.ToTable("planes_fondo", "productos");
                });

            modelBuilder.Entity("Products.Domain.Plans.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("PlanId");

                    b.ToTable("planes", "productos");
                });

            modelBuilder.Entity("Products.Domain.Portfolios.Portfolio", b =>
                {
                    b.Property<int>("PortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PortfolioId"));

                    b.Property<decimal>("AdditionalMinimumAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("aporte_minimo_adicional");

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("porcentaje_comision");

                    b.Property<int>("CommissionRateTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_tasa_comision");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actual");

                    b.Property<string>("HomologatedCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_homologacion");

                    b.Property<decimal>("InitialMinimumAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("aporte_minimo_inicial");

                    b.Property<int>("ModalityId")
                        .HasColumnType("integer")
                        .HasColumnName("modalidad_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_corto");

                    b.HasKey("PortfolioId");

                    b.ToTable("portafolios", "productos");
                });

            modelBuilder.Entity("Products.Domain.AlternativePortfolios.AlternativePortfolio", b =>
                {
                    b.HasOne("Products.Domain.Alternatives.Alternative", "Alternative")
                        .WithMany("Portfolios")
                        .HasForeignKey("AlternativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Products.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany("Alternatives")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alternative");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Products.Domain.Alternatives.Alternative", b =>
                {
                    b.HasOne("Products.Domain.PlanFunds.PlanFund", "PlanFund")
                        .WithMany("Alternatives")
                        .HasForeignKey("PlanFundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanFund");
                });

            modelBuilder.Entity("Products.Domain.ConfigurationParameters.ConfigurationParameter", b =>
                {
                    b.HasOne("Products.Domain.ConfigurationParameters.ConfigurationParameter", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Products.Domain.Objectives.Objective", b =>
                {
                    b.HasOne("Products.Domain.Alternatives.Alternative", "Alternative")
                        .WithMany("Objectives")
                        .HasForeignKey("AlternativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Products.Domain.Commercials.Commercial", "Commercial")
                        .WithMany()
                        .HasForeignKey("CommercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alternative");

                    b.Navigation("Commercial");
                });

            modelBuilder.Entity("Products.Domain.PlanFunds.PlanFund", b =>
                {
                    b.HasOne("Products.Domain.PensionFunds.PensionFund", "PensionFund")
                        .WithMany("PlanFunds")
                        .HasForeignKey("PensionFundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Products.Domain.Plans.Plan", "Plan")
                        .WithMany("PlanFunds")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PensionFund");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Products.Domain.Alternatives.Alternative", b =>
                {
                    b.Navigation("Objectives");

                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("Products.Domain.ConfigurationParameters.ConfigurationParameter", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Products.Domain.PensionFunds.PensionFund", b =>
                {
                    b.Navigation("PlanFunds");
                });

            modelBuilder.Entity("Products.Domain.PlanFunds.PlanFund", b =>
                {
                    b.Navigation("Alternatives");
                });

            modelBuilder.Entity("Products.Domain.Plans.Plan", b =>
                {
                    b.Navigation("PlanFunds");
                });

            modelBuilder.Entity("Products.Domain.Portfolios.Portfolio", b =>
                {
                    b.Navigation("Alternatives");
                });
#pragma warning restore 612, 618
        }
    }
}
