using Common.SharedKernel.Application.Messaging;

namespace Products.Integrations.ConfigurationParameters.GetConfigurationParameters;

public sealed record GetConfigurationParametersQuery : IQuery<IReadOnlyCollection<ConfigurationParameterResponse>>;