DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'personas') THEN
        CREATE SCHEMA personas;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS personas."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'personas') THEN
        CREATE SCHEMA personas;
    END IF;
END $EF$;

CREATE TABLE personas.actividades_economicas (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    codgrupo text NOT NULL,
    descripcion text NOT NULL,
    codigo_ciiu text NOT NULL,
    codigo_division text NOT NULL,
    nombre_division text NOT NULL,
    nombre_grupo text NOT NULL,
    codigo_clase text NOT NULL,
    codigo_homologado text NOT NULL,
    CONSTRAINT "PK_actividades_economicas" PRIMARY KEY (id)
);

CREATE TABLE personas.municipios (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo_ciudad integer NOT NULL,
    nombre text NOT NULL,
    indicativo integer NOT NULL,
    codigo_dane integer NOT NULL,
    codigo_homologado text NOT NULL,
    CONSTRAINT "PK_municipios" PRIMARY KEY (id)
);

CREATE TABLE personas.paises (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    nombre_abreviado text NOT NULL,
    codigo_dane text NOT NULL,
    codigo_homologado text NOT NULL,
    CONSTRAINT "PK_paises" PRIMARY KEY (id)
);

CREATE TABLE personas.parametros_configuracion (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    uuid uuid NOT NULL DEFAULT (uuid_generate_v4()),
    nombre character varying(100) NOT NULL,
    padre_id integer,
    estado boolean NOT NULL DEFAULT TRUE,
    tipo character varying(50) NOT NULL DEFAULT 'categoria',
    editable boolean NOT NULL DEFAULT TRUE,
    sistema boolean NOT NULL DEFAULT FALSE,
    metadata jsonb NOT NULL DEFAULT ('{}'),
    codigo_homologacion character varying(20) NOT NULL,
    CONSTRAINT "PK_parametros_configuracion" PRIMARY KEY (id),
    CONSTRAINT "FK_parametros_configuracion_parametros_configuracion_padre_id" FOREIGN KEY (padre_id) REFERENCES personas.parametros_configuracion (id) ON DELETE RESTRICT
);

CREATE TABLE personas.personas (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo_documento_uuid uuid NOT NULL,
    identificacion text NOT NULL,
    primer_nombre text NOT NULL,
    segundo_nombre text,
    primer_apellido text NOT NULL,
    segundo_apellido text,
    nombre_completo text NOT NULL,
    celular text NOT NULL,
    sexo_id integer NOT NULL,
    pais_residencia_id integer NOT NULL,
    departamento_id integer NOT NULL,
    municipio_id integer NOT NULL,
    email text NOT NULL,
    actividad_economica_id integer NOT NULL,
    direccion text NOT NULL,
    declarante boolean NOT NULL,
    tipo_inversionista_id integer NOT NULL,
    perfil_riesgo_id integer NOT NULL,
    estado text NOT NULL,
    codigo_homologado text NOT NULL,
    CONSTRAINT "PK_personas" PRIMARY KEY (id)
);

CREATE INDEX "IX_parametros_configuracion_padre_id" ON personas.parametros_configuracion (padre_id);

INSERT INTO personas."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250613050143_InitialCreate', '9.0.3');

COMMIT;

