START TRANSACTION;
CREATE TABLE personas.departamentos (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    codigo_dane integer NOT NULL,
    codigo_homologado text NOT NULL,
    CONSTRAINT "PK_departamentos" PRIMARY KEY (id)
);

INSERT INTO personas."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250613053551_AddDepartament', '9.0.3');

COMMIT;

