CREATE TABLE contabilidad.cuentas_contables (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cuenta character varying(20) NOT NULL,
    nombre character varying(50) NOT NULL,
    CONSTRAINT "PK_cuentas_contables" PRIMARY KEY (id)
);

INSERT INTO contabilidad."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251107133916_AddAccountingAccount', '9.0.3');


