CREATE TABLE contabilidad.configuraciones_generales (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    "portafolio_Id" integer NOT NULL,
    codigo_contable character varying(10) NOT NULL,
    centro_costos character varying(12) NOT NULL,
    CONSTRAINT "PK_configuraciones_generales" PRIMARY KEY (id)
);

CREATE TABLE contabilidad.consecutivos_archivo (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fecha_generacion timestamp with time zone NOT NULL,
    consecutivo integer NOT NULL,
    fecha_actual timestamp with time zone NOT NULL,
    CONSTRAINT "PK_consecutivos_archivo" PRIMARY KEY (id)
);

INSERT INTO contabilidad."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251026192444_AddNewTablesConfiguration', '9.0.3');


