DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'uuid-ossp') THEN
        CREATE EXTENSION "uuid-ossp";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'accounting') THEN
        CREATE SCHEMA accounting;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'contabilidad') THEN
        CREATE SCHEMA contabilidad;
    END IF;
END $$;
CREATE TABLE IF NOT EXISTS contabilidad."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'contabilidad') THEN
        CREATE SCHEMA contabilidad;
    END IF;
END $$;

CREATE TABLE contabilidad.auxiliar_contable (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    identificacion character varying(13) NOT NULL,
    digito_verificacion integer,
    nombre character varying(50) NOT NULL,
    periodo character varying(6),
    cuenta character varying(6),
    fecha timestamp with time zone,
    nit character varying(12),
    detalle character varying(100),
    tipo character varying(2) NOT NULL,
    valor numeric(19,2) NOT NULL DEFAULT 0.0,
    naturaleza character varying(20) NOT NULL,
    identificador bigint NOT NULL,
    CONSTRAINT "PK_auxiliar_contable" PRIMARY KEY (id)
);

CREATE TABLE contabilidad.conceptos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    portafolio_id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    cuenta_contra_credito character varying(20),
    cuenta_contra_debito character varying(20),
    cuenta_debito character varying(20),
    cuenta_credito character varying(20),
    CONSTRAINT "PK_conceptos" PRIMARY KEY (id)
);

CREATE TABLE contabilidad.consecutivos (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    naturaleza character varying(50) NOT NULL,
    documento_fuente character varying(4) NOT NULL,
    consecutivo integer NOT NULL,
    CONSTRAINT "PK_consecutivos" PRIMARY KEY (id)
);

CREATE TABLE contabilidad.parametros_configuracion (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    uuid uuid NOT NULL DEFAULT (uuid_generate_v4()),
    nombre character varying(100) NOT NULL,
    padre_id integer,
    estado boolean NOT NULL DEFAULT TRUE,
    tipo character varying(50) NOT NULL DEFAULT 'categoria',
    editable boolean NOT NULL DEFAULT TRUE,
    sistema boolean NOT NULL DEFAULT FALSE,
    metadata jsonb NOT NULL DEFAULT ('{}'),
    codigo_homologacion character varying(20) NOT NULL,
    CONSTRAINT "PK_parametros_configuracion" PRIMARY KEY (id),
    CONSTRAINT "FK_parametros_configuracion_parametros_configuracion_padre_id" FOREIGN KEY (padre_id) REFERENCES contabilidad.parametros_configuracion (id) ON DELETE RESTRICT
);

CREATE TABLE contabilidad.tesoreria (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    portafolio_id integer NOT NULL,
    cuenta_bancaria character varying(20),
    cuenta_debito character varying(20),
    cuenta_credito character varying(20),
    CONSTRAINT "PK_tesoreria" PRIMARY KEY (id)
);

CREATE TABLE contabilidad.transacciones_pasivas (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    portafolio_id integer NOT NULL,
    tipo_operaciones_id bigint NOT NULL,
    cuenta_debito character varying(20),
    cuenta_credito character varying(20),
    cuenta_contra_credito character varying(20),
    cuenta_contra_debito character varying(20),
    CONSTRAINT "PK_transacciones_pasivas" PRIMARY KEY (id)
);

CREATE INDEX "IX_parametros_configuracion_padre_id" ON contabilidad.parametros_configuracion (padre_id);

INSERT INTO contabilidad."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250915220200_InitialCreate', '9.0.3');


