DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'operaciones') THEN
        CREATE SCHEMA operaciones;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS operaciones."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'operaciones') THEN
        CREATE SCHEMA operaciones;
    END IF;
END $EF$;

CREATE TABLE operaciones."Bank" (
    "BankId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nit" text NOT NULL,
    "Name" text NOT NULL,
    "CompensationCode" integer NOT NULL,
    "Status" text NOT NULL,
    "HomologatedCode" text NOT NULL,
    "CheckClearingDays" integer NOT NULL,
    CONSTRAINT "PK_Bank" PRIMARY KEY ("BankId")
);

CREATE TABLE operaciones.canales (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    codigo_homologado text NOT NULL,
    sistema boolean NOT NULL,
    estado text NOT NULL,
    CONSTRAINT "PK_canales" PRIMARY KEY (id)
);

CREATE TABLE operaciones.origen_aportes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    obligatoriedad_originador boolean NOT NULL,
    exige_certificacion boolean NOT NULL,
    exige_retencion_contingente boolean NOT NULL,
    estado text NOT NULL,
    codigo_homologado text NOT NULL,
    CONSTRAINT "PK_origen_aportes" PRIMARY KEY (id)
);

CREATE TABLE operaciones.parametros_configuracion (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    uuid uuid NOT NULL DEFAULT (uuid_generate_v4()),
    nombre character varying(100) NOT NULL,
    padre_id integer,
    estado boolean NOT NULL DEFAULT TRUE,
    tipo character varying(50) NOT NULL DEFAULT 'categoria',
    editable boolean NOT NULL DEFAULT TRUE,
    sistema boolean NOT NULL DEFAULT FALSE,
    metadata jsonb NOT NULL DEFAULT ('{}'),
    codigo_homologacion character varying(20) NOT NULL,
    CONSTRAINT "PK_parametros_configuracion" PRIMARY KEY (id),
    CONSTRAINT "FK_parametros_configuracion_parametros_configuracion_padre_id" FOREIGN KEY (padre_id) REFERENCES operaciones.parametros_configuracion (id) ON DELETE RESTRICT
);

CREATE TABLE operaciones.subtipo_transacciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    categoria uuid NOT NULL,
    naturaleza text NOT NULL,
    estado text NOT NULL,
    externo text NOT NULL,
    codigo_homologado text NOT NULL,
    CONSTRAINT "PK_subtipo_transacciones" PRIMARY KEY (id)
);

CREATE TABLE operaciones."OriginMode" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OriginId" integer NOT NULL,
    "ModalityOriginId" integer NOT NULL,
    CONSTRAINT "PK_OriginMode" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OriginMode_origen_aportes_OriginId" FOREIGN KEY ("OriginId") REFERENCES operaciones.origen_aportes (id) ON DELETE CASCADE
);

CREATE TABLE operaciones.operaciones_clientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fecha_radicacion timestamp with time zone NOT NULL,
    afiliado_id integer NOT NULL,
    objetivo_id integer NOT NULL,
    portafolio_id integer NOT NULL,
    valor numeric NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    subtipo_transaccion_id bigint NOT NULL,
    CONSTRAINT "PK_operaciones_clientes" PRIMARY KEY (id),
    CONSTRAINT "FK_operaciones_clientes_subtipo_transacciones_subtipo_transacc~" FOREIGN KEY (subtipo_transaccion_id) REFERENCES operaciones.subtipo_transacciones (id) ON DELETE CASCADE
);

CREATE TABLE operaciones.informacion_auxiliar (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    operacion_cliente_id bigint NOT NULL,
    origen_id integer NOT NULL,
    metodo_recaudo_id integer NOT NULL,
    forma_pago_id integer NOT NULL,
    cuenta_recaudo integer NOT NULL,
    detalle_forma_pago jsonb NOT NULL,
    estado_certificacion_id integer NOT NULL,
    condicion_tributaria_id integer NOT NULL,
    retencion_contingente integer NOT NULL,
    medio_verificable jsonb NOT NULL,
    banco_recaudo integer NOT NULL,
    fecha_consignacion timestamp with time zone NOT NULL,
    usuario_comercial text NOT NULL,
    modalidad_origen_id integer NOT NULL,
    ciudad_id integer NOT NULL,
    canal_id integer NOT NULL,
    usuario_id integer NOT NULL,
    "BankId" integer NOT NULL,
    CONSTRAINT "PK_informacion_auxiliar" PRIMARY KEY (id),
    CONSTRAINT "FK_informacion_auxiliar_Bank_BankId" FOREIGN KEY ("BankId") REFERENCES operaciones."Bank" ("BankId") ON DELETE CASCADE,
    CONSTRAINT "FK_informacion_auxiliar_canales_canal_id" FOREIGN KEY (canal_id) REFERENCES operaciones.canales (id) ON DELETE CASCADE,
    CONSTRAINT "FK_informacion_auxiliar_operaciones_clientes_operacion_cliente~" FOREIGN KEY (operacion_cliente_id) REFERENCES operaciones.operaciones_clientes (id) ON DELETE CASCADE,
    CONSTRAINT "FK_informacion_auxiliar_origen_aportes_origen_id" FOREIGN KEY (origen_id) REFERENCES operaciones.origen_aportes (id) ON DELETE CASCADE
);

CREATE TABLE operaciones.operaciones_retiro_fideicomiso (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    operaciones_clientes_id bigint NOT NULL,
    fideicomiso_id bigint NOT NULL,
    valor numeric NOT NULL,
    CONSTRAINT "PK_operaciones_retiro_fideicomiso" PRIMARY KEY (id),
    CONSTRAINT "FK_operaciones_retiro_fideicomiso_operaciones_clientes_operaci~" FOREIGN KEY (operaciones_clientes_id) REFERENCES operaciones.operaciones_clientes (id) ON DELETE CASCADE
);

CREATE INDEX "IX_informacion_auxiliar_BankId" ON operaciones.informacion_auxiliar ("BankId");

CREATE INDEX "IX_informacion_auxiliar_canal_id" ON operaciones.informacion_auxiliar (canal_id);

CREATE UNIQUE INDEX "IX_informacion_auxiliar_operacion_cliente_id" ON operaciones.informacion_auxiliar (operacion_cliente_id);

CREATE INDEX "IX_informacion_auxiliar_origen_id" ON operaciones.informacion_auxiliar (origen_id);

CREATE INDEX "IX_operaciones_clientes_subtipo_transaccion_id" ON operaciones.operaciones_clientes (subtipo_transaccion_id);

CREATE INDEX "IX_operaciones_retiro_fideicomiso_operaciones_clientes_id" ON operaciones.operaciones_retiro_fideicomiso (operaciones_clientes_id);

CREATE UNIQUE INDEX "IX_OriginMode_OriginId" ON operaciones."OriginMode" ("OriginId");

CREATE INDEX "IX_parametros_configuracion_padre_id" ON operaciones.parametros_configuracion (padre_id);

INSERT INTO operaciones."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250613181106_InitialCreate', '9.0.3');

COMMIT;

