ALTER TABLE operaciones.operaciones_clientes DROP CONSTRAINT "FK_operaciones_clientes_subtipo_transacciones_subtipo_transacc~";

ALTER TABLE operaciones.operaciones_fideicomiso RENAME COLUMN subtipo_transaccion_id TO tipo_operaciones_id;

ALTER TABLE operaciones.operaciones_clientes_temporal RENAME COLUMN subtipo_transaccion_id TO tipo_operaciones_id;

ALTER TABLE operaciones.operaciones_clientes RENAME COLUMN subtipo_transaccion_id TO tipo_operaciones_id;

ALTER INDEX operaciones."IX_operaciones_clientes_subtipo_transaccion_id" RENAME TO "IX_operaciones_clientes_tipo_operaciones_id";

CREATE TABLE operaciones.tipos_operaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    categoria integer,
    naturaleza text NOT NULL,
    estado text NOT NULL,
    externo text NOT NULL,
    visible boolean NOT NULL,
    atributos_adicionales jsonb NOT NULL,
    codigo_homologado text NOT NULL,
    CONSTRAINT "PK_tipos_operaciones" PRIMARY KEY (id)
);


                INSERT INTO operaciones.tipos_operaciones
                    (nombre, categoria, naturaleza, estado, externo, visible, atributos_adicionales, codigo_homologado)
                VALUES
                    ('Aporte',       NULL, 'I', 'A', 'false', TRUE,  '{}'::jsonb, 'AP'),
                    ('Rendimientos', NULL, 'I', 'A', 'false', FALSE, '{}'::jsonb, 'U'),
                    ('Retiro Ágil',  NULL, 'E', 'A', 'false', FALSE, '{}'::jsonb, 'RE');
            


                INSERT INTO operaciones.tipos_operaciones
                    (nombre, categoria, naturaleza, estado, externo, visible, atributos_adicionales, codigo_homologado)
                VALUES
                    ('Ninguno',           (SELECT id FROM operaciones.tipos_operaciones WHERE nombre = 'Aporte' LIMIT 1), 'I', 'A', 'false', TRUE,  '{}'::jsonb, 'N'),
                    ('Descuento nomina',  (SELECT id FROM operaciones.tipos_operaciones WHERE nombre = 'Aporte' LIMIT 1), 'I', 'A', 'false', FALSE, '{}'::jsonb, 'DN'),
                    ('Debito Automatico', (SELECT id FROM operaciones.tipos_operaciones WHERE nombre = 'Aporte' LIMIT 1), 'I', 'A', 'false', FALSE, '{}'::jsonb, 'DA');
            


                UPDATE operaciones.operaciones_clientes oc
                SET tipo_operaciones_id = toper.id
                FROM operaciones.subtipo_transacciones st
                JOIN operaciones.tipos_operaciones toper
                  ON toper.codigo_homologado = st.codigo_homologado
                WHERE oc.tipo_operaciones_id = st.id;
            


                UPDATE operaciones.operaciones_clientes_temporal oct
                SET tipo_operaciones_id = toper.id
                FROM operaciones.subtipo_transacciones st
                JOIN operaciones.tipos_operaciones toper
                  ON toper.codigo_homologado = st.codigo_homologado
                WHERE oct.tipo_operaciones_id = st.id;
            


                UPDATE operaciones.operaciones_fideicomiso ofi
                SET tipo_operaciones_id = toper.id
                FROM operaciones.subtipo_transacciones st
                JOIN operaciones.tipos_operaciones toper
                  ON toper.codigo_homologado = st.codigo_homologado
                WHERE ofi.tipo_operaciones_id = st.id;
            

DROP TABLE operaciones.subtipo_transacciones;

ALTER TABLE operaciones.operaciones_clientes ADD CONSTRAINT "FK_operaciones_clientes_tipos_operaciones_tipo_operaciones_id" FOREIGN KEY (tipo_operaciones_id) REFERENCES operaciones.tipos_operaciones (id) ON DELETE CASCADE;

INSERT INTO operaciones."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250813144444_RefactorSubtransactionTypeToHierarchicalOperationType', '9.0.3');


