DROP TABLE operaciones.operaciones_retiro_fideicomiso;

ALTER TABLE operaciones.operaciones_clientes ADD fecha_aplicacion timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

CREATE TABLE operaciones.operaciones_fideicomiso (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    operaciones_clientes_id bigint NOT NULL,
    fideicomiso_id bigint NOT NULL,
    valor numeric NOT NULL,
    subtipo_transaccion_id bigint NOT NULL,
    portafolio_id integer NOT NULL,
    fecha_radicacion timestamp with time zone NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    fecha_aplicacion timestamp with time zone NOT NULL,
    CONSTRAINT "PK_operaciones_fideicomiso" PRIMARY KEY (id),
    CONSTRAINT "FK_operaciones_fideicomiso_operaciones_clientes_operaciones_cl~" FOREIGN KEY (operaciones_clientes_id) REFERENCES operaciones.operaciones_clientes (id) ON DELETE CASCADE
);

CREATE INDEX "IX_operaciones_fideicomiso_operaciones_clientes_id" ON operaciones.operaciones_fideicomiso (operaciones_clientes_id);

INSERT INTO operaciones."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250627131521_ReplaceTrustWithdrawalWithTrustOperation', '9.0.3');


