START TRANSACTION;
ALTER TABLE operaciones.informacion_auxiliar DROP CONSTRAINT "FK_informacion_auxiliar_Bank_BankId";

ALTER TABLE operaciones."OriginMode" DROP CONSTRAINT "FK_OriginMode_origen_aportes_OriginId";

ALTER TABLE operaciones."OriginMode" DROP CONSTRAINT "PK_OriginMode";

ALTER TABLE operaciones."Bank" DROP CONSTRAINT "PK_Bank";

ALTER TABLE operaciones."OriginMode" RENAME TO origenaportes_modorigen;

ALTER TABLE operaciones."Bank" RENAME TO bancos;

ALTER TABLE operaciones.origenaportes_modorigen RENAME COLUMN "Id" TO id;

ALTER TABLE operaciones.origenaportes_modorigen RENAME COLUMN "OriginId" TO origen_id;

ALTER TABLE operaciones.origenaportes_modorigen RENAME COLUMN "ModalityOriginId" TO modalidad_origen_id;

ALTER INDEX operaciones."IX_OriginMode_OriginId" RENAME TO "IX_origenaportes_modorigen_origen_id";

ALTER TABLE operaciones.bancos RENAME COLUMN "Nit" TO nit;

ALTER TABLE operaciones.bancos RENAME COLUMN "Status" TO estado;

ALTER TABLE operaciones.bancos RENAME COLUMN "Name" TO nombre;

ALTER TABLE operaciones.bancos RENAME COLUMN "HomologatedCode" TO codigo_homologado;

ALTER TABLE operaciones.bancos RENAME COLUMN "CompensationCode" TO codigo_compensacion;

ALTER TABLE operaciones.bancos RENAME COLUMN "CheckClearingDays" TO dias_de_canje_cheques;

ALTER TABLE operaciones.bancos RENAME COLUMN "BankId" TO id;

ALTER TABLE operaciones.origenaportes_modorigen ADD CONSTRAINT "PK_origenaportes_modorigen" PRIMARY KEY (id);

ALTER TABLE operaciones.bancos ADD CONSTRAINT "PK_bancos" PRIMARY KEY (id);

CREATE TABLE operaciones."Banks" (
    "BankId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Banks" PRIMARY KEY ("BankId")
);

ALTER TABLE operaciones.informacion_auxiliar ADD CONSTRAINT "FK_informacion_auxiliar_bancos_BankId" FOREIGN KEY ("BankId") REFERENCES operaciones.bancos (id) ON DELETE CASCADE;

ALTER TABLE operaciones.origenaportes_modorigen ADD CONSTRAINT "FK_origenaportes_modorigen_origen_aportes_origen_id" FOREIGN KEY (origen_id) REFERENCES operaciones.origen_aportes (id) ON DELETE RESTRICT;

INSERT INTO operaciones."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250613183655_ChangeName', '9.0.3');

COMMIT;

