CREATE TABLE operaciones.operaciones_clientes_temporal (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fecha_radicacion timestamp with time zone NOT NULL,
    afiliado_id integer NOT NULL,
    objetivo_id integer NOT NULL,
    portafolio_id integer NOT NULL,
    valor numeric NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    subtipo_transaccion_id bigint NOT NULL,
    fecha_aplicacion timestamp with time zone NOT NULL,
    CONSTRAINT "PK_operaciones_clientes_temporal" PRIMARY KEY (id)
);

CREATE TABLE operaciones.informacion_auxiliar_temporal (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    operacion_cliente_temporal_id bigint NOT NULL,
    origen_id integer NOT NULL,
    metodo_recaudo_id integer NOT NULL,
    forma_pago_id integer NOT NULL,
    cuenta_recaudo integer NOT NULL,
    detalle_forma_pago jsonb NOT NULL,
    estado_certificacion_id integer NOT NULL,
    condicion_tributaria_id integer NOT NULL,
    retencion_contingente integer NOT NULL,
    medio_verificable jsonb NOT NULL,
    banco_recaudo integer NOT NULL,
    fecha_consignacion timestamp with time zone NOT NULL,
    usuario_comercial text NOT NULL,
    modalidad_origen_id integer NOT NULL,
    ciudad_id integer NOT NULL,
    canal_id integer NOT NULL,
    usuario_id integer NOT NULL,
    CONSTRAINT "PK_informacion_auxiliar_temporal" PRIMARY KEY (id),
    CONSTRAINT "FK_informacion_auxiliar_temporal_operaciones_clientes_temporal~" FOREIGN KEY (operacion_cliente_temporal_id) REFERENCES operaciones.operaciones_clientes_temporal (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_informacion_auxiliar_temporal_operacion_cliente_temporal_id" ON operaciones.informacion_auxiliar_temporal (operacion_cliente_temporal_id);

INSERT INTO operaciones."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250709045704_AddTemporaryOperationsTables', '9.0.3');


