namespace Treasury.IntegrationEvents.TreasuryMovements.ValidateExistByPortfolioAndAccountNumber;

public sealed record ValidateExistByPortfolioAndAccountNumberRequest(long PortfolioId, string AccountNumber);
