// <auto-generated />
using System;
using Associate.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Associate.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ActivatesDbContext))]
    [Migration("20250514152000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("afiliado")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Associate.Domain.Activates.Activate", b =>
                {
                    b.Property<int>("ActivateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("activación_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActivateId"));

                    b.Property<DateTime>("ActivateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_activación");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identificacion");

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_identificacion");

                    b.Property<bool>("MeetsPensionRequirements")
                        .HasColumnType("boolean")
                        .HasColumnName("cumple_requisitos_pension");

                    b.Property<bool>("Pensioner")
                        .HasColumnType("boolean")
                        .HasColumnName("pendionado");

                    b.HasKey("ActivateId")
                        .HasName("pk_activacion_afiliado");

                    b.ToTable("activacion_afiliado", "afiliado");
                });
#pragma warning restore 612, 618
        }
    }
}
