CREATE TABLE fideicomisos.parametros_configuracion (
    parametro_configuracion_id integer GENERATED BY DEFAULT AS IDENTITY,
    uuid uuid NOT NULL DEFAULT (uuid_generate_v4()),
    nombre character varying(100) NOT NULL,
    padre_id integer,
    estado boolean NOT NULL DEFAULT TRUE,
    tipo character varying(50) NOT NULL DEFAULT 'categoria',
    editable boolean NOT NULL DEFAULT TRUE,
    sistema boolean NOT NULL DEFAULT FALSE,
    metadata jsonb NOT NULL DEFAULT ('{}'),
    codigo_homologacion character varying(20) NOT NULL,
    CONSTRAINT "PK_parametros_configuracion" PRIMARY KEY (parametro_configuracion_id),
    CONSTRAINT "FK_parametros_configuracion_parametros_configuracion_padre_id" FOREIGN KEY (padre_id) REFERENCES fideicomisos.parametros_configuracion (parametro_configuracion_id) ON DELETE RESTRICT
);

CREATE INDEX "IX_parametros_configuracion_padre_id" ON fideicomisos.parametros_configuracion (padre_id);

INSERT INTO fideicomisos."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250519145133_AddConfigurationParameters', '9.0.3');


