DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'fideicomisos') THEN
        CREATE SCHEMA fideicomisos;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS fideicomisos."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'fideicomisos') THEN
        CREATE SCHEMA fideicomisos;
    END IF;
END $EF$;

CREATE TABLE fideicomisos.fideicomisos (
    fideicomiso_id bigint GENERATED BY DEFAULT AS IDENTITY,
    afiliado_id integer NOT NULL,
    cliente_id integer NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    objetivo_id integer NOT NULL,
    portafolio_id integer NOT NULL,
    saldo_total numeric NOT NULL,
    unidades_totales integer NOT NULL,
    capital numeric NOT NULL,
    rendimiento numeric NOT NULL,
    condicion_tributaria integer NOT NULL,
    retencion_contingente numeric NOT NULL,
    retencion_rendimiento numeric NOT NULL,
    disponible numeric NOT NULL,
    porcentaje_retencion_contingente numeric NOT NULL,
    CONSTRAINT "PK_fideicomisos" PRIMARY KEY (fideicomiso_id)
);

CREATE TABLE fideicomisos.historicos_fideicomisos (
    historico_fideicomiso_id bigint GENERATED BY DEFAULT AS IDENTITY,
    "TrustId" bigint NOT NULL,
    rendimiento numeric NOT NULL,
    fecha timestamp with time zone NOT NULL,
    comercial_id text NOT NULL,
    CONSTRAINT "PK_historicos_fideicomisos" PRIMARY KEY (historico_fideicomiso_id),
    CONSTRAINT "FK_historicos_fideicomisos_fideicomisos_TrustId" FOREIGN KEY ("TrustId") REFERENCES fideicomisos.fideicomisos (fideicomiso_id) ON DELETE CASCADE
);

CREATE INDEX "IX_historicos_fideicomisos_TrustId" ON fideicomisos.historicos_fideicomisos ("TrustId");

INSERT INTO fideicomisos."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250514133839_InitialCreate', '9.0.3');

COMMIT;

