START TRANSACTION;
CREATE TABLE seguridad.logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fecha timestamp with time zone NOT NULL,
    accion text NOT NULL,
    usuario text NOT NULL,
    ip text NOT NULL,
    maquina text NOT NULL,
    descripcion text NOT NULL,
    objeto jsonb NOT NULL,
    estado_anterior_objeto jsonb NOT NULL,
    proceso_exitoso boolean NOT NULL,
    CONSTRAINT "PK_logs" PRIMARY KEY (id)
);

INSERT INTO seguridad."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250728191126_AddAuditLogsTable', '9.0.3');


