DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'uuid-ossp') THEN
        CREATE EXTENSION "uuid-ossp";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'treasury') THEN
        CREATE SCHEMA treasury;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'tesoreria') THEN
        CREATE SCHEMA tesoreria;
    END IF;
END $$;
CREATE TABLE IF NOT EXISTS tesoreria."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'tesoreria') THEN
        CREATE SCHEMA tesoreria;
    END IF;
END $$;

CREATE TABLE tesoreria.conceptos_tesoreria (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    concepto text NOT NULL,
    naturaleza text NOT NULL,
    admite_negativo boolean NOT NULL,
    permite_gasto boolean NOT NULL,
    cuenta_bancaria boolean NOT NULL,
    contraparte boolean NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    observaciones text NOT NULL,
    CONSTRAINT "PK_conceptos_tesoreria" PRIMARY KEY (id)
);

CREATE TABLE tesoreria.emisor (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    emisor text NOT NULL,
    descripcion text NOT NULL,
    nit real NOT NULL,
    digito integer NOT NULL,
    codigo_homologado text NOT NULL,
    CONSTRAINT "PK_emisor" PRIMARY KEY (id)
);

CREATE TABLE tesoreria.parametros_configuracion (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    uuid uuid NOT NULL DEFAULT (uuid_generate_v4()),
    nombre character varying(100) NOT NULL,
    padre_id integer,
    estado boolean NOT NULL DEFAULT TRUE,
    tipo character varying(50) NOT NULL DEFAULT 'categoria',
    editable boolean NOT NULL DEFAULT TRUE,
    sistema boolean NOT NULL DEFAULT FALSE,
    metadata jsonb NOT NULL DEFAULT ('{}'),
    codigo_homologacion character varying(20) NOT NULL,
    CONSTRAINT "PK_parametros_configuracion" PRIMARY KEY (id),
    CONSTRAINT "FK_parametros_configuracion_parametros_configuracion_padre_id" FOREIGN KEY (padre_id) REFERENCES tesoreria.parametros_configuracion (id) ON DELETE RESTRICT
);

CREATE TABLE tesoreria.cuenta_bancaria (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    portafolio_id bigint NOT NULL,
    emisor_id bigint NOT NULL,
    numero_cuenta text NOT NULL,
    tipo_cuenta text NOT NULL,
    observaciones text NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    CONSTRAINT "PK_cuenta_bancaria" PRIMARY KEY (id),
    CONSTRAINT "FK_cuenta_bancaria_emisor_emisor_id" FOREIGN KEY (emisor_id) REFERENCES tesoreria.emisor (id) ON DELETE CASCADE
);

CREATE TABLE tesoreria.movimientos_tesoreria (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    portafolio_id integer NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    fecha_cierre timestamp with time zone NOT NULL,
    concepto_tesoreria_id bigint NOT NULL,
    valor numeric(19,2) NOT NULL,
    cuenta_bancaria_id bigint,
    entidad_id bigint NOT NULL,
    contraparte_id bigint,
    CONSTRAINT "PK_movimientos_tesoreria" PRIMARY KEY (id),
    CONSTRAINT "FK_movimientos_tesoreria_conceptos_tesoreria_concepto_tesoreri~" FOREIGN KEY (concepto_tesoreria_id) REFERENCES tesoreria.conceptos_tesoreria (id) ON DELETE CASCADE,
    CONSTRAINT "FK_movimientos_tesoreria_cuenta_bancaria_cuenta_bancaria_id" FOREIGN KEY (cuenta_bancaria_id) REFERENCES tesoreria.cuenta_bancaria (id),
    CONSTRAINT "FK_movimientos_tesoreria_emisor_contraparte_id" FOREIGN KEY (contraparte_id) REFERENCES tesoreria.emisor (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_movimientos_tesoreria_emisor_entidad_id" FOREIGN KEY (entidad_id) REFERENCES tesoreria.emisor (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_cuenta_bancaria_emisor_id" ON tesoreria.cuenta_bancaria (emisor_id);

CREATE INDEX "IX_movimientos_tesoreria_concepto_tesoreria_id" ON tesoreria.movimientos_tesoreria (concepto_tesoreria_id);

CREATE INDEX "IX_movimientos_tesoreria_contraparte_id" ON tesoreria.movimientos_tesoreria (contraparte_id);

CREATE INDEX "IX_movimientos_tesoreria_cuenta_bancaria_id" ON tesoreria.movimientos_tesoreria (cuenta_bancaria_id);

CREATE INDEX "IX_movimientos_tesoreria_entidad_id" ON tesoreria.movimientos_tesoreria (entidad_id);

CREATE INDEX "IX_parametros_configuracion_padre_id" ON tesoreria.parametros_configuracion (padre_id);

INSERT INTO tesoreria."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250709162738_InitialCreate', '9.0.3');


