namespace Products.Integrations.Portfolios;

public sealed record CompletePortfolioInformationResponse(
    int PortfolioId,
    string Name,
    string ShortName,
    int ModalityId,
    decimal InitialMinimumAmount,
    decimal AdditionalMinimumAmount,
    DateTime CurrentDate,
    string HomologatedCode,
    int VerificationDigit,
    string PortfolioNIT,
    string NitApprovedPortfolio,
    Guid RiskProfile,
    int SFCBusinessCode,
    Guid Custodian,
    Guid Qualifier,
    Guid Rating,
    Guid RatingType,
    DateTime LastRatingDate,
    Guid AdviceClassification,
    int MaxParticipationPercentage,
    decimal MinimumVirPercentage,
    decimal PartialVirPercentage,
    int AgileWithdrawalPercentageProtectedBalance,
    int WithdrawalPercentageProtectedBalance,
    bool AllowsAgileWithdrawal,
    int PermanencePeriod,
    int PenaltyPercentage,
    DateTime OperationsStartDate,
    DateTime PortfolioExpiryDate,
    Guid IndustryClassification,
    string Status
);
