CREATE TABLE productos.salarios_minimos (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    anio text NOT NULL,
    valor numeric NOT NULL,
    CONSTRAINT "PK_salarios_minimos" PRIMARY KEY (id)
);

INSERT INTO productos."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251223140802_CreateMinimumWage', '9.0.3');


