CREATE TABLE productos.ficha_tecnica (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    portafolio_id integer NOT NULL,
    fecha timestamp with time zone NOT NULL,
    aportes numeric(19,2) NOT NULL,
    retiros numeric(19,2) NOT NULL,
    pyg_bruto numeric(19,2) NOT NULL,
    gastos numeric(19,2) NOT NULL,
    comision_dia numeric(19,2) NOT NULL,
    costo_dia numeric(19,2) NOT NULL,
    rendimientos_abonados numeric(19,2) NOT NULL,
    rendimiento_bruto_unidad numeric(38,16) NOT NULL,
    costo_unidad numeric(38,16) NOT NULL,
    valor_unidad numeric(38,16) NOT NULL,
    unidades numeric(38,16) NOT NULL,
    valor_portafolio numeric(19,2) NOT NULL,
    participes integer NOT NULL,
    CONSTRAINT pk_ficha_tecnica PRIMARY KEY (id),
    CONSTRAINT fk_ficha_tecnica_portafolios_portafolio_id FOREIGN KEY (portafolio_id) REFERENCES productos.portafolios (id) ON DELETE CASCADE
);

CREATE INDEX ix_ficha_tecnica_portafolio_id ON productos.ficha_tecnica (portafolio_id);

CREATE INDEX ix_ficha_tecnica_fecha ON productos.ficha_tecnica (fecha);

INSERT INTO productos."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250811180109_CreateNewTableFichaTecnica', '9.0.3');


