START TRANSACTION;
ALTER TABLE productos.fondos_voluntarios_pensiones RENAME COLUMN tipo_documento TO tipo_identificacion;

ALTER TABLE productos.fondos_voluntarios_pensiones ALTER COLUMN identificacion TYPE character varying(25);

ALTER TABLE productos.fondos_voluntarios_pensiones ADD digito integer NOT NULL DEFAULT 0;

CREATE TABLE productos.administradores (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    identificacion character varying(25) NOT NULL,
    tipo_identificacion integer NOT NULL,
    digito integer NOT NULL,
    nombre character varying(100) NOT NULL,
    estado text NOT NULL,
    codigo_entidad character varying(6) NOT NULL,
    tipo_entidad integer NOT NULL,
    CONSTRAINT "PK_administradores" PRIMARY KEY (id)
);


                INSERT INTO productos.administradores
                    (id, identificacion, tipo_identificacion, digito, nombre, estado, codigo_entidad, tipo_entidad)
                VALUES
                    (
                        1,
                        '800150280',
                        (SELECT id FROM productos.parametros_configuracion 
                         WHERE tipo = 'TipoDocumento' AND nombre = 'Nit de la Sociedad' LIMIT 1),
                        0,
                        'Fiduciaria Bancolombia',
                        'A',
                        '00531',
                        (SELECT id FROM productos.parametros_configuracion 
                         WHERE tipo = 'TipoEntidad' AND nombre = 'SOCIEDADES FIDUCIARIAS' LIMIT 1)
                    )
                ON CONFLICT DO NOTHING;
            

ALTER TABLE productos.fondos_voluntarios_pensiones ADD administrador_id integer;


                UPDATE productos.fondos_voluntarios_pensiones
                SET administrador_id = 1
                WHERE administrador_id IS NULL;
            

UPDATE productos.fondos_voluntarios_pensiones SET administrador_id = 1 WHERE administrador_id IS NULL;
ALTER TABLE productos.fondos_voluntarios_pensiones ALTER COLUMN administrador_id SET NOT NULL;
ALTER TABLE productos.fondos_voluntarios_pensiones ALTER COLUMN administrador_id SET DEFAULT 1;

CREATE INDEX "IX_fondos_voluntarios_pensiones_administrador_id" ON productos.fondos_voluntarios_pensiones (administrador_id);

ALTER TABLE productos.fondos_voluntarios_pensiones ADD CONSTRAINT "FK_fondos_voluntarios_pensiones_administradores_administrador_id" FOREIGN KEY (administrador_id) REFERENCES productos.administradores (id) ON DELETE CASCADE;

INSERT INTO productos."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250826142922_AddAdministratorTableAndLinkToPensionFunds', '9.0.3');


