CREATE TABLE productos.comisiones (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id integer NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    concepto character varying(100) NOT NULL,
    modalidad character varying(100) NOT NULL,
    tipo_comision character varying(50) NOT NULL,
    periodo character varying(50) NOT NULL,
    base_calculo character varying(200) NOT NULL,
    regla_calculo character varying(2000) NOT NULL,
    activo text NOT NULL,
    CONSTRAINT "PK_comisiones" PRIMARY KEY (id),
    CONSTRAINT "FK_comisiones_portafolios_portfolio_id" FOREIGN KEY (portfolio_id) REFERENCES productos.portafolios (id) ON DELETE CASCADE
);

CREATE TABLE productos.valoracion_portafolio_dia (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id integer NOT NULL,
    fecha_cierre timestamp with time zone NOT NULL,
    valor numeric(19,2) NOT NULL,
    unidades numeric(38,16) NOT NULL,
    valor_unidad numeric(19,2) NOT NULL,
    rendimiento_bruto_unidad numeric(38,16) NOT NULL,
    costo_unidad numeric(38,16) NOT NULL,
    rentabilidad_diaria numeric(38,16) NOT NULL,
    operaciones_entrada numeric(19,2) NOT NULL,
    operaciones_salida numeric(19,2) NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    CONSTRAINT "PK_valoracion_portafolio_dia" PRIMARY KEY (id),
    CONSTRAINT "FK_valoracion_portafolio_dia_portafolios_portfolio_id" FOREIGN KEY (portfolio_id) REFERENCES productos.portafolios (id) ON DELETE CASCADE
);

CREATE TABLE productos.comisiones_acumuladas (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id integer NOT NULL,
    comisiones_id integer NOT NULL,
    valor_acumulado numeric(19,2) NOT NULL,
    valor_pagado numeric(19,2) NOT NULL,
    valor_pendiente numeric(19,2) NOT NULL,
    fecha_cierre timestamp with time zone NOT NULL,
    fecha_pago timestamp with time zone NOT NULL,
    fecha_proceso timestamp with time zone NOT NULL,
    CONSTRAINT "PK_comisiones_acumuladas" PRIMARY KEY (id),
    CONSTRAINT "FK_comisiones_acumuladas_comisiones_comisiones_id" FOREIGN KEY (comisiones_id) REFERENCES productos.comisiones (id) ON DELETE CASCADE
);

CREATE INDEX "IX_comisiones_portfolio_id" ON productos.comisiones (portfolio_id);

CREATE INDEX "IX_comisiones_acumuladas_comisiones_id" ON productos.comisiones_acumuladas (comisiones_id);

CREATE INDEX "IX_valoracion_portafolio_dia_portfolio_id" ON productos.valoracion_portafolio_dia (portfolio_id);

INSERT INTO productos."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250627131507_AddCommissionAndPortfolioValuationEntities', '9.0.3');


