DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'afiliados') THEN
        CREATE SCHEMA afiliados;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS afiliados."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'afiliados') THEN
        CREATE SCHEMA afiliados;
    END IF;
END $EF$;

CREATE TABLE afiliados.activacion_afiliados (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    tipo_documento_uuid uuid NOT NULL,
    identificacion text NOT NULL,
    pensionado boolean NOT NULL,
    cumple_requisitos_pension boolean NOT NULL,
    fecha_activacion timestamp with time zone NOT NULL,
    CONSTRAINT "PK_activacion_afiliados" PRIMARY KEY (id)
);

CREATE TABLE afiliados.parametros_configuracion (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    uuid uuid NOT NULL DEFAULT (uuid_generate_v4()),
    nombre character varying(100) NOT NULL,
    padre_id integer,
    estado boolean NOT NULL DEFAULT TRUE,
    tipo character varying(50) NOT NULL DEFAULT 'categoria',
    editable boolean NOT NULL DEFAULT TRUE,
    sistema boolean NOT NULL DEFAULT FALSE,
    metadata jsonb NOT NULL DEFAULT ('{}'),
    codigo_homologacion character varying(20) NOT NULL,
    CONSTRAINT "PK_parametros_configuracion" PRIMARY KEY (id),
    CONSTRAINT "FK_parametros_configuracion_parametros_configuracion_padre_id" FOREIGN KEY (padre_id) REFERENCES afiliados.parametros_configuracion (id) ON DELETE RESTRICT
);

CREATE TABLE afiliados.requisitos_pension (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    afiliado_id integer NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_vencimiento timestamp with time zone NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    estado text NOT NULL,
    CONSTRAINT "PK_requisitos_pension" PRIMARY KEY (id),
    CONSTRAINT "FK_requisitos_pension_activacion_afiliados_afiliado_id" FOREIGN KEY (afiliado_id) REFERENCES afiliados.activacion_afiliados (id) ON DELETE CASCADE
);

CREATE INDEX "IX_parametros_configuracion_padre_id" ON afiliados.parametros_configuracion (padre_id);

CREATE INDEX "IX_requisitos_pension_afiliado_id" ON afiliados.requisitos_pension (afiliado_id);

INSERT INTO afiliados."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250613054407_InitialCreate', '9.0.3');

COMMIT;

